### ISSUE TITLE
Error message with version esi v1806

### ISSUE THREAD

**Issue by fab6** [ITHACA-FV/ITHACA-FV#153]
Hi all,

I just tried to install the tools with openfoam version v1806.
Even though this version is not listed, maybe anyone has a hint for some changes to get it to work? This would be great!

Thanks in advance!
Best Regards Fab

Below is my error message:
g++ -std=c++11 -m64 -DOPENFOAM=1806 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas -O3  -DNoRepository -ftemplate-depth-100 -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/TurbulenceModels/turbulenceModels/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/TurbulenceModels/incompressible/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/TurbulenceModels/compressible/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/transportModels -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/transportModels/incompressible/singlePhaseTransportModel -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/finiteVolume/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/meshTools/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/dynamicMesh/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/sampling/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/fileFormats/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/dynamicFvMesh/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/thermophysicalModels/basic/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/thermophysicalModels/radiation/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/turbulenceModels/compressible/turbulenceModel -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/transportModels/compressible/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/functionObjects/forces/lnInclude -I/share/Tools/AI/CFD/ITHACA-FV/src/thirdparty/spectra/include -I/share/Tools/AI/CFD/ITHACA-FV/src/thirdparty/Eigen -I/share/Tools/AI/CFD/ITHACA-FV/src/thirdparty/redsvd -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACAutilities -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACAstream -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACAPOD -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACADMD -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/EigenFunctions -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/Foam2Eigen -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ForceCoeff -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/Containers -Wall -Wno-comment -DOFVER=${WM_PROJECT_VERSION%.*} -std=c++11 -IlnInclude -I. -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OSspecific/POSIX/lnInclude   -fPIC -c Containers/Modes.C -o Make/linux64GccDPInt32Opt/Containers/Modes.o
ITHACAutilities/ITHACAforces.C: In member function ‘virtual void Foam::functionObjects::ITHACAforces::writeFileHeader(Foam::label)’:
ITHACAutilities/ITHACAforces.C:1135:31: error: no matching function for call to ‘Foam::functionObjects::ITHACAforces::file(const label&)’
             writeHeader(file(i), "Forces");
                               ^
ITHACAutilities/ITHACAforces.C:1135:31: note: candidate is:
In file included from /share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude/logFiles.H:43:0,
                 from ITHACAutilities/ITHACAforces.H:30,
                 from ITHACAutilities/ITHACAforces.C:1080:
/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude/writeFile.H:154:27: note: virtual Foam::OFstream& Foam::functionObjects::writeFile::file()
         virtual OFstream& file();
                           ^
/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude/writeFile.H:154:27: note:   candidate expects 0 arguments, 1 provided
ITHACAutilities/ITHACAforces.C:1136:36: error: no matching function for call to ‘Foam::functionObjects::ITHACAforces::file(const label&)’
             writeHeaderValue(file(i), "CofR", coordSys_.origin());
                                    ^
ITHACAutilities/ITHACAforces.C:1136:36: note: candidate is:
In file included from /share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude/logFiles.H:43:0,
                 from ITHACAutilities/ITHACAforces.H:30,
                 from ITHACAutilities/ITHACAforces.C:1080:
/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude/writeFile.H:154:27: note: virtual Foam::OFstream& Foam::functionObjects::writeFile::file()
         virtual OFstream& file();

**Comment by giovastabile** [comment]
Hi @fab6, in case there are no other big differences between OF1806 and OF1812 I think it is enough to change everywhere in the code this line:
#if OPENFOAM >= 1812
with this
#if OPENFOAM >= 1806

It is an if statement that tells the compiler which lines of code it should compile, at the moment since your version is smaller than 1812 it uses the lines defined for the foundation version and it can't compile.

In case it works please let me know and I will change it also in the public version or if you prefer you can directly do a pull request.

Best,

Giovanni

**Comment by fab6** [comment]
Hi Giovanni,

thank you! Though after I changed it in a few lines I get:
-I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OSspecific/POSIX/lnInclude   -fPIC -c Containers/Modes.C -o Make/linux64GccDPInt32Opt/Containers/Modes.o
In file included from Containers/Modes.C:35:0:
Containers/Modes.H:42:23: fatal error: Eigen/Eigen: No such file or directory
 #include <Eigen/Eigen>
                       ^
compilation terminated.
/share/software/OpenFOAM/ESI/OpenFOAM-v1806/wmake/rules/General/transform:34: recipe for target 'Make/linux64GccDPInt32Opt/Containers/Modes.o' failed
make: *** [Make/linux64GccDPInt32Opt/Containers/Modes.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from EigenFunctions/EigenFunctions.C:31:0:
EigenFunctions/EigenFunctions.H:42:23: fatal error: Eigen/Eigen: No such file or directory
 #include <Eigen/Eigen>
                       ^

Maybe, there are a few more changes... 

Best Regards
Fab

**Comment by giovastabile** [comment]
It should be ok now, you have simply to follow the instructions on the GitHub page. You forgot to source the bashrc file of ITHACA. Before compiling you should do:

source etc/bashrc

**Comment by fab6** [comment]
yes, that's right, I forgot it. Thanks for the help!

**Comment by fab6** [comment]
sorry for the trouble... now I get:

g++ -std=c++11 -m64 -DOPENFOAM=1806 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtu
al-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas -O3  -DNoRepository -ftemplate-depth-100 -I/sh
are/software/OpenFOAM/ESI/OpenFOAM-v1806/src/TurbulenceModels/turbulenceModels/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/
src/TurbulenceModels/incompressible/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/TurbulenceModels/compressible/lnInclude
 -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/transportModels -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/transportModels/in
compressible/singlePhaseTransportModel -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/finiteVolume/lnInclude -I/share/software/OpenF
OAM/ESI/OpenFOAM-v1806/src/meshTools/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/dynamicMesh/lnInclude -I/share/softwar
e/OpenFOAM/ESI/OpenFOAM-v1806/src/sampling/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/fileFormats/lnInclude -I/share/s
oftware/OpenFOAM/ESI/OpenFOAM-v1806/src/dynamicFvMesh/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/thermophysicalModels/
basic/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/thermophysicalModels/radiation/lnInclude -I/share/software/OpenFOAM/E
SI/OpenFOAM-v1806/src/turbulenceModels/compressible/turbulenceModel -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/transportModels/c
ompressible/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/functionObjects/forces/lnInclude -I/share/Tools/AI/CFD/ITHACA-F
V/src/thirdparty/spectra/include -I/share/Tools/AI/CFD/ITHACA-FV/src/thirdparty/Eigen -I/share/Tools/AI/CFD/ITHACA-FV/src/thirdparty/re
dsvd -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACAutilities -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACAstream -I/sh
are/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACAPOD -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/ITHACADMD -I/share/Tools/AI/CFD/IT
HACA-FV/src/ITHACA_CORE/EigenFunctions -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/Foam2Eigen -I/share/Tools/AI/CFD/ITHACA-FV/src/I
THACA_CORE/ForceCoeff -I/share/Tools/AI/CFD/ITHACA-FV/src/ITHACA_CORE/Containers -Wall -Wno-comment -DOFVER=${WM_PROJECT_VERSION%.*} -s
td=c++11 -IlnInclude -I. -I/share/software/OpenFOAM/ESI/OpenFOAM-v1806/src/OpenFOAM/lnInclude -I/share/software/OpenFOAM/ESI/OpenFOAM-v
1806/src/OSspecific/POSIX/lnInclude   -fPIC -c Containers/Modes.C -o Make/linux64GccDPInt32Opt/Containers/Modes.o
In file included from ITHACAutilities/ITHACAforces.C:33:0:
ITHACAutilities/ITHACAforces18.H:119:9: error: 'coordSystem' does not name a type
         coordSystem::cartesian coordSys_;
         ^
ITHACAutilities/ITHACAforces.C: In member function 'void Foam::functionObjects::ITHACAforces::writeIntegratedHeader(const Foam::word&,
Foam::Ostream&) const':
ITHACAutilities/ITHACAforces.C:106:34: error: 'coordSys_' was not declared in this scope
     writeHeaderValue(os, "CofR", coordSys_.origin());

**Comment by fab6** [comment]
I will check to install v1812...

**Comment by giovastabile** [comment]
Ok that's an issue with the differences between OF1806 and OF1812. Yes I
suggest you to install OF1812

Il ven 14 giu 2019, 20:56 fab6 <notifications@github.com> ha scritto:

**Comment by fab6** [comment]
ok, thank you for your support! Have a nice weekend!

**Comment by olesenm** [comment]
The coordinate systems and rotations were substantially cleaned up for 1812, which resulted in some changes in the namespaces. To ease going *forward* there is a corresponding typedef:

```
//- Compatibility typedef 1806
typedef coordSystem::cartesian cartesianCS
```

But since Giovanni's code was already adapted for 1812 it uses the newer naming, and there's no typedef possible to go in that direction.

**Comment by fab6** [comment]
Thank you for the help as well, I forgot to mention it, but it runs now with a new 1812 installation. Thanks and Greetings
