### ISSUE TITLE
Some issues with RAM

### ISSUE THREAD

**Issue by guillaumeLepape** [ITHACA-FV/ITHACA-FV#243]
Hello, 

I'm a student and I'm trying to use ITHACA-FV for a one of my project. I ran some tutorials in order to create my own case. However, I've trying to run the program with large offline data (approximately 150 Go). When ITHACA put snapshots in RAM, it fails because I'm using a desktop computer with 16 Go of RAM, so it was expected to cause some issues. I can't use a other computer so I'm asking if you try to launch simulation with large data in desktop computer and if it's true how you deal with these issues. Maybe you used better computers with larger RAM to do it and ITHACA-FV wasn't provide for what I'm trying to do.

Regards.

GuIllaume

**Comment by giovastabile** [comment]
Dear Guillaume, 

we have used ITHACA-FV with relatively large cases so in principle there should not be any issue if you have a sufficient amount of RAM. Most of the RAM is used to store the snapshots before the calculation of the POD modes. You could try to slightly modify the code in order to make such operation more efficient and avoid storing all the snapshots altogether. At which point of the simulation do you exactly notice that you run out of memory? Can I have more details on the problem that you are trying to solve?

Giovanni

**Comment by guillaumeLepape** [comment]
Thanks for your response,

I have run an OpenFoam standard case which a unsteady incompressible flow passing around a cylinder in 2D during 1200 s at Reynolds = 100. The mesh is about 150 000 points. My export time step is equal to 0.05. So this makes 24000 snapshots. I wanted to make POD between 600 and 1200 s. As the tutorial 4, I didn't put any parameter dependence except time. So I have used perform_POD command to make POD, the program is reading the speed field and I get, as excepted, ```Reading snapshot nb_snapshot for field U```. But at a certain point, I just get `Process stopped`. In order to understand the issue, I rerun the command and look my RAM during the execution. And the RAM pass from 13 Go to 0. To solve the problem, I search in the perform_POD.C file. I saw that the speed snapshots is put in RAM by the command `Vfield.append(*vector_field);`. Maybe, I should load the snapshots differently to overcome the problem.

Guillaume.

**Comment by giovastabile** [comment]
Yes exactly, in order to compute the POD you need to have all the snapshots but you can anyway compute the correlation matrix which is necessary to perform the POD element by element. This would need a bit of extra programming but you can still do what you need.

**Comment by guillaumeLepape** [comment]
Thanks for your answers.
