### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [ITHACA-FV/ITHACA-FV#268]
Hi,

I wonder whether you have ever considered to make a feature request to OpenFOAM in order to release `ITHACA-FV` as a module under the official OpenFOAM banner in the long term?

For example, `OpenQBMM`, `avalanche`, `PETSc` and `adios` have recently been shipped as [modules](https://develop.openfoam.com/Development/openfoam/-/tree/develop/modules). [sedFoam](https://github.com/SedFoam/sedfoam/issues/15) and `solid4Foam` had been showing interest to do so as well.

In my opinion, it would be a win-win for the users and your code suite.

Kind regards,
Kuti

**Comment by giovastabile** [comment]
Dear @KutalmisBercin we have never considered such a thing but we would happy to release ITHACA-FV as an official module. This would increase the number of users and in the long term also the quality of the code.  

Regards,

Giovanni Stabile

**Comment by olesenm** [comment]
Hi @giovastabile - not sure you remember me from Braunschweig last year? 
If you are indeed interested, then open a GitLab issue (develop.openfoam.com) for discussion there. This helps for internal audit trails and later integration.

Cheers, 
/mark

**Comment by giovastabile** [comment]
Hi @olesenm, yes sure I remember you well. I will open an issue on GitLab and we will continue the discussion there. 

Cheers,

Giovanni

**Comment by ghost** [comment]
Thank you very much @giovastabile.

Assumed the request to be migrated to GitLab.
