### ISSUE TITLE
PPE not working with tutorial4

### ISSUE THREAD

**Issue by Helen-xq** [ITHACA-FV/ITHACA-FV#273]
Dear Author,
Thank you for the great POD code. 
I am trying to change the project method to PPE in tutorial 04, but it does not work.  According to my test, it fails in solving the steadyNS::pressure BC3(label NUmodes, label NPmodes).  I tried lift and penalty options for bcMethod in ITHACAdict. it does not matter. I am a beginner for C++ and POD methods, please advise how to modify the code to use PPE method in tutorial 04. I only modified the projectSUP, solveOnline_SUP, and reconstruct_SUP to projectPPE, solveOnline_PPE and reconstruct_PPE. Could you provide an example for mu_samples_mat.txt? I give one constant 0.005 in my mu_samples_mat.txt. Is it correct? 
Looking forward to your kind help.

Best regards
Helen

**Comment by giovastabile** [comment]
Thanks, we will have a look at it and we will let you know. @saddamhijazi @ksstar @MatteoZancanaro 

Giovanni

**Comment by saddamhijazi** [comment]
@Helen-xq  Hello, sorry for the very late response, I have tested now the tutorial for the PPE case and it seems to work. As you mentioned you just need to replace  projectSUP, solveOnline_SUP, and reconstruct_SUP by projectPPE, solveOnline_PPE and reconstruct_PPE, respectively. Also don't forget to comment the following lines

example.solvesupremizer();

ITHACAPOD::getModes(example.supfield, example.supmodes, example._U().name(),
example.podex,
example.supex, 1, NmodesSUPout);

I would also suggest to modify the number of modes in the ITHACdict dictionary to the following:

// Number of modes to output and to use for projection
NmodesUout 50;
NmodesUproj 12;

NmodesPout 50;
NmodesPproj 12;

NmodesSUPout 50;
NmodesSUPproj 12;


Could you try again and let me know what you get.

Best regards,
Saddam

**Comment by Helen-xq** [comment]
Saddam, 

Thank you for the detailed information. I will test it and get back to you. 

best regards
Helen
