### ISSUE TITLE
Online Stage Solving Issue in Tutorial 06

### ISSUE THREAD

**Issue by andiraarif** [ITHACA-FV/ITHACA-FV#295]
Dear authors,
Thank you for publishing such a great code on ROM for OpenFOAM. However, I have an issue regarding the online solving process particularly in tutorial 06. The default 06POD_RBF application seems to solve the online stage right away after completing the offline stage and it works really well. Now, what I would like to do is to perform offline and online stages separately by simply truncating the 06POD_RBF code until the offline stage, and once after it has been finished I run the default and I get the error message like this. 

![image](https://user-images.githubusercontent.com/25652547/94538720-8ec70d80-026e-11eb-9f5a-7a1ac30a04bd.png)

Is it possible to perform the offline-online stage separately? If yes, could you please tell me the way to do that? 
Thank you

Best regards,
Arif

**Comment by giovastabile** [comment]
Probably you truncated the offline stage before the computation of the POD modes but the folder has been already created but it is empty. Try to delete all the folders inside ITHACAoutput apart from the Offline folder.

**Comment by andiraarif** [comment]
Dear Dr. Giovanni Stabile,
Thank you for your advice, it works successfully! Actually, I truncated the code after computing the reduced-order matrices as shown below. It is because I think that the next step will be starting to perform the online stage. Is it true? Could you provide guidance on where I should truncate the code or tips about performing separate offline-online stage calculations?

Thank you, I really appreciate your response and support.

Best regards,
Arif

**Comment by andiraarif** [comment]
Thank you very much, Sir, it works for me!
