### ISSUE TITLE
Cannot compile with clang

### ISSUE THREAD

**Issue by olesenm** [ITHACA-FV/ITHACA-FV#352]
@giovastabile
I suspect there are a few places in your code that will be problematic with label-size 64 and single precision. Prior to checking that however, it makes sense to check the overall C++ compliance. 
I currently use clang 11 when compiling OpenFOAM since gcc tends to be much too forgiving. 
I gave this a quick try with your code and it highlighted several issues (refused to compile).

**Comment by giovastabile** [comment]
Fixed in #387
