### ISSUE TITLE
Issues in parallel run for 02ThermalBlock

### ISSUE THREAD

**Issue by carpemonf-zz** [ITHACA-FV/ITHACA-FV#395]
Hi @giovastabile,

I'm trying to execute a parallel run for one of the tutorials (02ThermalBlock). After a first try I got the following error:

```
[0]
[0]
[0] --> FOAM FATAL ERROR: (openfoam-2012)
[0] cannot find file "/home/ofuser/app/tutorials/CFD/02thermalBlockParallel/processor0/./system/ITHACAdict"
[0]
[0]     From virtual Foam::autoPtr<Foam::ISstream> Foam::fileOperations::uncollatedFileOperation::readStream(Foam::regIOobject&, const Foam::fileName&, const Foam::word&, bool) const
[0]     in file global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.C at line 547.
[0]
FOAM parallel run exiting
```

I fixed that by replacing the ITHACAdict path definition in line 15 `src/ITHACA_CORE/ITHACAstream/ITHACAparameters.C` to point to the system folder in parallel runs:  

```diff
- "./system"
+ localTime().system()
```

This allowed the execution of the whole process, but some issues appeared around the processor interfaces for the ROM results. Comparing results on `FOMtest` and `Reconstruction` folders for parallel runs with 2 and 4 processors I got the following:

2 processors:
![parallel_comparison_2](https://user-images.githubusercontent.com/4426168/129236178-f8b4d2d7-436e-42dc-894d-f3442cb26263.png)

4 processors:
![parallel_comparison_4](https://user-images.githubusercontent.com/4426168/129236022-02fc8213-333c-40b4-8aad-e7d2dcdb6c50.png)

Do you know why this might happen?

Thanks!
Carlos.

# Steps to reproduce the issue

The above was tested with `ithacafv/openfoam2012-muq2-pytorch` docker image:

1. Modifying `tutorials/CFD/02ThermalBlock/Allrun`
```diff
+ decomposePar
- runApplication 02thermalBlock
+ runParallel 02thermalBlock
```

2. Adding the following file `tutorials/CFD/02ThermalBlock/system/decomposeParDict`
```
/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  v1906                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      decomposeParDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

numberOfSubdomains 2;

method          scotch;

// ************************************************************************* /
```

3. Execute `./Allrun`

**Comment by giovastabile** [comment]
Thanks for reporting the issue. I should have fixed the things with #396. There was a problem in the parallel computation of the POD modes and the reduced operators were not correctly computed. I also changed ITHACAparameters according to your suggestion. I still need to experiment a bit the things with parallel cases. In case you notice any other issues please let me know.

GS

**Comment by carpemonf-zz** [comment]
Many thanks for the fix. It worked well for me. I think an `exit(0)` slipped through in the `02thermalBlock.C` after the POD decomposition.

I noticed some errors on the logs. It doesn't seem to affect results but Im sharing just in case:

```
[1e1469bc23a5:02433] Read -1, expected 2000024, errno = 1
[1e1469bc23a5:02431] Read -1, expected 2000024, errno = 1
[1e1469bc23a5:02431] Read -1, expected 2000024, errno = 1
[1e1469bc23a5:02433] Read -1, expected 2000024, errno = 1
[1e1469bc23a5:02432] Read -1, expected 2000024, errno = 1
[1e1469bc23a5:02434] Read -1, expected 2000024, errno = 1
```

It seems to come from `ITHACAPOD.C` [line 144](https://github.com/mathLab/ITHACA-FV/blob/master/src/ITHACA_CORE/ITHACAPOD/ITHACAPOD.C#L144):

```
        if (Pstream::parRun())
        {
            reduce(_corMatrix, sumOp<Eigen::MatrixXd>());
        }
```

Best!
Carlos.

**Comment by giovastabile** [comment]
Thanks, @carpemonf, yes I was checking that the normalization of the POD modes was working also in the parallel case and I forgot to remove the exit. I will investigate the error but I assume it should not create any issue.
