### ISSUE TITLE
when I learn the tetorials/CFD/01POD, I can not use the 'perform_POD' utility to extract the modes, it is displayed that './Allrun: 93: perform_POD: not found' in log-perform_POD 

### ISSUE THREAD

**Issue by heushanghe** [ITHACA-FV/ITHACA-FV#544]
when I learn the tetorials/CFD/01POD,after getting the solution by 'icoFoam' ,I can not use the 'perform_POD' utility to extract the modes, it is displayed that './Allrun: 93: perform_POD: not found' in log-perform_POD .why this happens....

**Comment by giovastabile** [comment]
Because you need to compile applications as well. 

Compile the library with ./Allwmake -tau 

Everything is reported on github webpage

**Comment by heushanghe** [comment]
oh~ thanks for your answer a lot
