### ISSUE TITLE
Redundant code `exportSolution`

### ISSUE THREAD

**Issue by ndem0** [ITHACA-FV/ITHACA-FV#61]
Messed overload of `exportSolution` method:
`void reductionProblem::exportSolution(T& s, fileName subfolder, fileName folder)`
`void ITHACAstream::exportSolution(T& s, fileName subfolder, fileName folder, word fieldName)`

I suggest to put both the implementations in the same file and to try to reuse the code.

**Comment by giovastabile** [comment]
Yes, semantically the second one is the correct one. We should remove the first one.

**Comment by ndem0** [comment]
Fix in #74
