### ISSUE TITLE
ITHACAstream::readMatrix extra empty row

### ISSUE THREAD

**Issue by ksstar** [ITHACA-FV/ITHACA-FV#77]
The Eigen::MatrixXd ITHACAstream::readMatrix(word filename) function in ITHACA_CORE/ITHACAstream/ITHACAstream.C gives as a result 1 extra row for the matrix that is being read. 

Example: reading in matrix of size 2(rows)x2(cols) gives as a result a matrix of 3x2 with an empty last row.

Suggestion to solve issue: add "rows--;" after "infile.close();" as was the case in a previous version of ITHACA-FV.

**Comment by ndem0** [comment]
Fixed in #78
